/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import { Provider } from '@ethersproject/providers'
import type {
	IMarketBehavior,
	IMarketBehaviorInterface,
} from '../IMarketBehavior'

const _abi = [
	{
		inputs: [],
		name: 'associatedMarket',
		outputs: [
			{
				internalType: 'address',
				name: '',
				type: 'address',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: '_prop',
				type: 'address',
			},
			{
				internalType: 'string[]',
				name: '_args',
				type: 'string[]',
			},
			{
				internalType: 'address',
				name: 'account',
				type: 'address',
			},
		],
		name: 'authenticate',
		outputs: [
			{
				internalType: 'bool',
				name: '',
				type: 'bool',
			},
		],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: '_metrics',
				type: 'address',
			},
		],
		name: 'getId',
		outputs: [
			{
				internalType: 'string',
				name: '',
				type: 'string',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'string',
				name: '_id',
				type: 'string',
			},
		],
		name: 'getMetrics',
		outputs: [
			{
				internalType: 'address',
				name: '',
				type: 'address',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'name',
		outputs: [
			{
				internalType: 'string',
				name: '',
				type: 'string',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'schema',
		outputs: [
			{
				internalType: 'string',
				name: '',
				type: 'string',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'address',
				name: '_market',
				type: 'address',
			},
		],
		name: 'setAssociatedMarket',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
]

export class IMarketBehavior__factory {
	static readonly abi = _abi
	static createInterface(): IMarketBehaviorInterface {
		return new utils.Interface(_abi) as IMarketBehaviorInterface
	}
	static connect(
		address: string,
		signerOrProvider: Signer | Provider
	): IMarketBehavior {
		return new Contract(address, _abi, signerOrProvider) as IMarketBehavior
	}
}
