/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
	ethers,
	EventFilter,
	Signer,
	BigNumber,
	BigNumberish,
	PopulatedTransaction,
	BaseContract,
	ContractTransaction,
	Overrides,
	CallOverrides,
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

interface MockMarketFactoryInterface extends ethers.utils.Interface {
	functions: {
		'create(address)': FunctionFragment
		'latestMarketAddress()': FunctionFragment
	}

	encodeFunctionData(functionFragment: 'create', values: [string]): string
	encodeFunctionData(
		functionFragment: 'latestMarketAddress',
		values?: undefined
	): string

	decodeFunctionResult(functionFragment: 'create', data: BytesLike): Result
	decodeFunctionResult(
		functionFragment: 'latestMarketAddress',
		data: BytesLike
	): Result

	events: {}
}

export class MockMarketFactory extends BaseContract {
	connect(signerOrProvider: Signer | Provider | string): this
	attach(addressOrName: string): this
	deployed(): Promise<this>

	listeners<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
	): Array<TypedListener<EventArgsArray, EventArgsObject>>
	off<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>
	): this
	on<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>
	): this
	once<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>
	): this
	removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>
	): this
	removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
	): this

	listeners(eventName?: string): Array<Listener>
	off(eventName: string, listener: Listener): this
	on(eventName: string, listener: Listener): this
	once(eventName: string, listener: Listener): this
	removeListener(eventName: string, listener: Listener): this
	removeAllListeners(eventName?: string): this

	queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
		event: TypedEventFilter<EventArgsArray, EventArgsObject>,
		fromBlockOrBlockhash?: string | number | undefined,
		toBlock?: string | number | undefined
	): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

	interface: MockMarketFactoryInterface

	functions: {
		create(
			_behavior: string,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>

		latestMarketAddress(overrides?: CallOverrides): Promise<[string]>
	}

	create(
		_behavior: string,
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>

	latestMarketAddress(overrides?: CallOverrides): Promise<string>

	callStatic: {
		create(_behavior: string, overrides?: CallOverrides): Promise<void>

		latestMarketAddress(overrides?: CallOverrides): Promise<string>
	}

	filters: {}

	estimateGas: {
		create(
			_behavior: string,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>

		latestMarketAddress(overrides?: CallOverrides): Promise<BigNumber>
	}

	populateTransaction: {
		create(
			_behavior: string,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>

		latestMarketAddress(
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>
	}
}
